# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_user_anniversary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anniversary',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
