# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180326_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='added_items',
            field=models.ManyToManyField(related_name='item_adder', to='first_app.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='wished_for_items',
            field=models.ManyToManyField(related_name='wished_for_by_users', to='first_app.Item'),
        ),
    ]
